// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesRecordImport.DataAccess.EFCore;

namespace SalesRecordImport.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(SalesRecordDbContext))]
    [Migration("20190907190108_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalesRecordImport.Domain.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<long>("ExternalId");

                    b.Property<string>("ItemType");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("OrderPriority");

                    b.Property<string>("Region");

                    b.Property<int>("SalesChannel");

                    b.Property<DateTime>("ShipDate");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalProfit")
                        .HasColumnType("money");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<decimal>("UnitsSold")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("Country");

                    b.ToTable("SalesRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
